Enable a bunch of pylint checks
angr/angr-dev pull request #123
Opened 2021-06-17 00:48 UTC by twizmwazin

2021-06-17 19:03 UTC, rhelmot requested changes
we should also add `abstract-method` to the disable list.

2021-06-22 21:31 UTC, twizmwazin commented
Re-added `locally-enabled, locally-disabled, len-as-condition, no-else-return`. @rhelmot What do you think about `missing-docstring`? Otherwise good to merge if you're happy with this.

2021-06-22 23:44 UTC, rhelmot commented
Let's require docstrings on classes but not modules or functions.

2021-06-23 01:11 UTC, rhelmot approved these changes

2021-06-23 01:12 UTC, merged